export {default as Home} from "./pages/home/home";
export {default as Login} from "./profile/login";
export {default as Profile} from "./profile/profile";
export {default as Navbar} from "./header/navbar";
export {default as Footer} from "./footer/footer";
export {default as Catalog} from "./pages/catalog/catalog"
export {default as AboutUs} from './pages/aboutus/about-us'
export {default as Contact} from "./pages/contact/contact"
export {default as ConfirmOrder} from "./pages/confirm-order/confirm-order"
export {default as Cart} from "./pages/cart/cart"